export const rpgConfig = {
  startingStats: {
    hp: 100,
    maxHp: 100,
    attack: 8,
    defense: 6,
    cunning: 5,
    xp: 0,
    level: 1,
    gold: 0,
  },
  levelThresholds: [0, 50, 120, 200, 300, 450],
  partyMembers: {
    grimjaw: {
      name: "Grimjaw",
      role: "Bruiser",
      hp: 120,
      maxHp: 120,
      attack: 12,
      defense: 8,
      cunning: 3,
      bond: 0,
      icon: "💪",
      description: "A massive, scarred veteran who fights for gold and glory.",
    },
    lyralei: {
      name: "Lyralei",
      role: "Wandering Mage",
      hp: 60,
      maxHp: 60,
      attack: 4,
      defense: 3,
      cunning: 14,
      bond: 0,
      icon: "🔮",
      description: "A young mage seeking to prove her skills beyond the academy walls.",
    },
    silas: {
      name: "Silas",
      role: "The Ferryman",
      hp: 90,
      maxHp: 90,
      attack: 15,
      defense: 10,
      cunning: 12,
      bond: 0,
      icon: "🗡️",
      description: "A master assassin disguised as a simple boatman. Dangerous and unpredictable.",
    },
  },
  bondDescriptions: {
    grimjaw: {
      stranger: "Walks behind you, hand resting on his weapon.",
      acquaintance: "Grunts approvingly at your decisions.",
      companion: "Cracks jokes about your swordsmanship.",
      friend: "Tells you about his family over ale.",
      trustedAlly: "Calls you brother.",
    },
    lyralei: {
      stranger: "Studies her scrolls and keeps to herself.",
      acquaintance: "Shares a piece of travel bread with you.",
      companion: "Explains the history of places you pass.",
      friend: "Teaches you a minor cantrip by the campfire.",
      trustedAlly: "Trusts you with her most powerful spells.",
    },
    silas: {
      stranger: "Watches everyone with an assassin's eyes.",
      acquaintance: "Offers a backhanded compliment about your fighting.",
      companion: "Shares a dark joke and almost smiles.",
      friend: "Reveals a hidden safe route through dangerous ground.",
      trustedAlly: "Swears a blood oath of loyalty to your cause.",
    },
  },
};
